### ISSUE TITLE
Quick question old 3ds/2ds

### ISSUE THREAD

**Issue by Alexyo21** [CarsonKompon/ChatGPT3DS#2]
Hi sorry for bothering, is it just untested or just doesn't work on old type consoles?
Thanks.

**Comment by CarsonKompon** [comment]
I haven't tested on an o3DS/o2DS, however it should work just fine other than image generation taking a significantly longer amount of time to load the image due to the processing power of the device.

If you happen to run the application on one of those devices and have issues, please open another issue :)

**Comment by Alexyo21** [comment]
> I haven't tested on an o3DS/o2DS, however it should work just fine other than image generation taking a significantly longer amount of time to load the image due to the processing power of the device.
> 
> If you happen to run the application on one of those devices and have issues, please open another issue :)

Ok thanks a lot for the answer, I noticed now cause the issue was closed.
Thanks again for your kindness
